### ISSUE TITLE
I am getting ValueError that num_samples should be positive number

### ISSUE THREAD

**Issue by Saurabh262000** [xuyu0010/ARID_v1#3]
I think the problem lie in taking model directory address or pretrained weight address or Video data address, please look into it.

**ValueError: num_samples should be a positive integer value, but got num_samples=0**
![Screenshot from 2022-04-21 13-56-42](https://user-images.githubusercontent.com/64847406/164415151-6fd4c3b1-2651-44d4-b40e-8998da3f1f60.png)
![Screenshot from 2022-04-21 13-57-08](https://user-images.githubusercontent.com/64847406/164415356-64c96afe-fe65-48fe-88b9-98674c7f5dbc.png)

**Comment by Lakshyadevelops** [comment]
@Saurabh262000   Could you explain how you solved it? I guess the dataset to train is not at correct location.
